apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  containers:
    - name: hello
      image: {{ .Values.imageRegistry }}/hello-socket:{{ .Values.dockerTag }}
      args: {{ .Values.helloArgs | toJson }}
  restartPolicy: OnFailure
