---
- name: Remove unecessary packages
  apt:
    autoremove: yes

- name: Cleanup apt cache
  command: apt-get clean && apt-get autoclean

- name: Fill empty space with zeros
  command: dd if=/dev/zero of=/zero bs=1M
  ignore_errors: yes

- name: Sync filesystem
  command: sync

- name: Free zero filled space
  file:
    path: '/zero'
    state: absent

- name: Sync filesystem
  command: sync
