---
- name: Upgrade OS
  apt:
    upgrade: dist
    update_cache: yes

- name: Modify hostname
  hostname:
    name: '{{ hostname }}'
  when: hostname is defined

- name: Remove old /etc/hosts data
  lineinfile:
    path: '/etc/hosts'
    regexp: '127.0.1.1.*ubuntu-bionic'
    state: absent
  when: hostname is defined

- name: Insert new hostname into /etc/hosts
  lineinfile:
    path: '/etc/hosts'
    regexp: '(127.0.0.1.*localhost)'
    line: '\1\t{{ hostname }}\t{{ hostname.split(".")[0] }}'
  when: hostname is defined

- name: Install common debian packages
  apt:
    name: '{{ debian_pkgs | default([]) }}'

- name: Download pip installer
  get_url:
    url: 'https://bootstrap.pypa.io/get-pip.py'
    dest: '/tmp'

- name: Install pip2
  shell: 'python /tmp/get-pip.py'

- name: Install pip3
  shell: 'python3 /tmp/get-pip.py'

- name: Cleanup pip installer
  file:
    path: '/tmp/get-pip.py'
    state: absent

- name: Install common Python2 packages
  pip:
    name: '{{ python_pkgs | default([]) }}'
    executable: 'pip2'

- name: Install common Python3 packages
  pip:
    name: '{{ python_pkgs | default([]) }}'
    executable: 'pip3'
