---
- name: Setup OS
  hosts: default
  become: yes
  roles:
    - common-linux
  vars:
    hostname: 'sandbox-minikube.acs.local'

- name: Setup Sandbox environment
  hosts: default
  become: yes
  roles:
    - virtualbox-guest-additions
    - geerlingguy.java
    - iac-utils
    - minikube
  vars:
    java_packages:
      - openjdk-11-jdk

- name: User configuration
  hosts: default
  roles:
    - minikube-config

- name: Cleanup image
  hosts: default
  become: yes
  roles:
    - common-image-cleanup
